import Head from 'next/head';

export default function SEO() {
  return (
    <Head>
      <title>lol-github-profile-api</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/assets/logow.png" />
    </Head>
  );
}
